name: Deploy doxygen document.

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "document"
  cancel-in-progress: false

jobs:
  # Build and deploy doxygen document.
  build:
    name: Build doxygen document.
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen action.
        id: build
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: "./Doxyfile"

      - name: Upload artifact.
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html

  # Deploy to GitHub Pages.
  deploy:
    name: Deploy doxygen document.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages.
        id: deployment
        uses: actions/deploy-pages@v4