name: Unit Test (macOS, clang)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: |
          brew update
          brew install cmake
          brew install llvm

      - name: Configure CMake
        run: |
          export CC=/opt/homebrew/opt/llvm/bin/clang
          export CXX=/opt/homebrew/opt/llvm/bin/clang++
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Run Test
        run: ${{github.workspace}}/build/test/google_tests_run