name: Unit Test (Windows, MSVC)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: |
          cmake -B ./build -DCMAKE_BUILD_TYPE=Debug -DTEST=ON

      - name: Build
        run: cmake --build ./build

      - name: Run Test
        run: ${{github.workspace}}/build/test/google_tests_run